# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _gslwrap
else:
    import _gslwrap

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


PYGSL_TYPEMAPS_PYGSL_COMPAT_I = _gslwrap.PYGSL_TYPEMAPS_PYGSL_COMPAT_I

_PyGSL_SWIG_INIT_H_ = _gslwrap._PyGSL_SWIG_INIT_H_

M_E = _gslwrap.M_E

M_LOG2E = _gslwrap.M_LOG2E

M_LOG10E = _gslwrap.M_LOG10E

M_SQRT2 = _gslwrap.M_SQRT2

M_SQRT1_2 = _gslwrap.M_SQRT1_2

M_SQRT3 = _gslwrap.M_SQRT3

M_PI = _gslwrap.M_PI

M_PI_2 = _gslwrap.M_PI_2

M_PI_4 = _gslwrap.M_PI_4

M_SQRTPI = _gslwrap.M_SQRTPI

M_2_SQRTPI = _gslwrap.M_2_SQRTPI

M_1_PI = _gslwrap.M_1_PI

M_2_PI = _gslwrap.M_2_PI

M_LN10 = _gslwrap.M_LN10

M_LN2 = _gslwrap.M_LN2

M_LNPI = _gslwrap.M_LNPI

M_EULER = _gslwrap.M_EULER

GSL_POSZERO = _gslwrap.GSL_POSZERO

GSL_NEGZERO = _gslwrap.GSL_NEGZERO


def gsl_log1p(x):
    r"""
    gsl_log1p(double const x) -> double

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_log1p(x)

def gsl_expm1(x):
    r"""
    gsl_expm1(double const x) -> double

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_expm1(x)

def gsl_hypot(x, y):
    r"""
    gsl_hypot(double const x, double const y) -> double

    Parameters
    ----------
    x: double const
    y: double const

    """
    return _gslwrap.gsl_hypot(x, y)

def gsl_hypot3(x, y, z):
    r"""
    gsl_hypot3(double const x, double const y, double const z) -> double

    Parameters
    ----------
    x: double const
    y: double const
    z: double const

    """
    return _gslwrap.gsl_hypot3(x, y, z)

def gsl_acosh(x):
    r"""
    gsl_acosh(double const x) -> double

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_acosh(x)

def gsl_asinh(x):
    r"""
    gsl_asinh(double const x) -> double

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_asinh(x)

def gsl_atanh(x):
    r"""
    gsl_atanh(double const x) -> double

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_atanh(x)

def gsl_isnan(x):
    r"""
    gsl_isnan(double const x) -> int

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_isnan(x)

def gsl_isinf(x):
    r"""
    gsl_isinf(double const x) -> int

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_isinf(x)

def gsl_finite(x):
    r"""
    gsl_finite(double const x) -> int

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_finite(x)

def gsl_nan():
    r"""gsl_nan() -> double"""
    return _gslwrap.gsl_nan()

def gsl_posinf():
    r"""gsl_posinf() -> double"""
    return _gslwrap.gsl_posinf()

def gsl_neginf():
    r"""gsl_neginf() -> double"""
    return _gslwrap.gsl_neginf()

def gsl_fdiv(x, y):
    r"""
    gsl_fdiv(double const x, double const y) -> double

    Parameters
    ----------
    x: double const
    y: double const

    """
    return _gslwrap.gsl_fdiv(x, y)

def gsl_coerce_double(x):
    r"""
    gsl_coerce_double(double const x) -> double

    Parameters
    ----------
    x: double const

    """
    return _gslwrap.gsl_coerce_double(x)

def gsl_coerce_float(x):
    r"""
    gsl_coerce_float(float const x) -> float

    Parameters
    ----------
    x: float const

    """
    return _gslwrap.gsl_coerce_float(x)

def gsl_coerce_long_double(x):
    r"""
    gsl_coerce_long_double(long double const x) -> long double

    Parameters
    ----------
    x: long double const

    """
    return _gslwrap.gsl_coerce_long_double(x)

def gsl_ldexp(x, e):
    r"""
    gsl_ldexp(double const x, int const e) -> double

    Parameters
    ----------
    x: double const
    e: int const

    """
    return _gslwrap.gsl_ldexp(x, e)

def gsl_frexp(x, e):
    r"""
    gsl_frexp(double const x, int * e) -> double

    Parameters
    ----------
    x: double const
    e: int *

    """
    return _gslwrap.gsl_frexp(x, e)

def gsl_fcmp(x1, x2, epsilon):
    r"""
    gsl_fcmp(double const x1, double const x2, double const epsilon) -> int

    Parameters
    ----------
    x1: double const
    x2: double const
    epsilon: double const

    """
    return _gslwrap.gsl_fcmp(x1, x2, epsilon)
class gsl_interp_accel(object):
    r"""Proxy of C gsl_interp_accel struct."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(gsl_interp_accel self) -> gsl_interp_accel"""
        _gslwrap.gsl_interp_accel_swiginit(self, _gslwrap.new_gsl_interp_accel())
    __swig_destroy__ = _gslwrap.delete_gsl_interp_accel

    def reset(self):
        r"""reset(gsl_interp_accel self) -> gsl_error_flag_drop"""
        return _gslwrap.gsl_interp_accel_reset(self)

    def find(self, x_array, x):
        r"""
        find(gsl_interp_accel self, double const [] x_array, double x) -> size_t

        Parameters
        ----------
        x_array: double const []
        x: double

        """
        return _gslwrap.gsl_interp_accel_find(self, x_array, x)

    def tocobject(self):
        r"""tocobject(gsl_interp_accel self) -> PyObject *"""
        return _gslwrap.gsl_interp_accel_tocobject(self)

# Register gsl_interp_accel in _gslwrap:
_gslwrap.gsl_interp_accel_swigregister(gsl_interp_accel)
class pygsl_lite_spline(object):
    r"""Proxy of C pygsl_lite_spline struct."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, T, n):
        r"""
        __init__(pygsl_lite_spline self, gsl_interp_type const * T, size_t n) -> pygsl_lite_spline

        Parameters
        ----------
        T: gsl_interp_type const *
        n: size_t

        """
        _gslwrap.pygsl_lite_spline_swiginit(self, _gslwrap.new_pygsl_lite_spline(T, n))
    __swig_destroy__ = _gslwrap.delete_pygsl_lite_spline

    def accel_reset(self):
        r"""accel_reset(pygsl_lite_spline self) -> gsl_error_flag_drop"""
        return _gslwrap.pygsl_lite_spline_accel_reset(self)

    def accel_find(self, x):
        r"""
        accel_find(pygsl_lite_spline self, double x) -> size_t

        Parameters
        ----------
        x: double

        """
        return _gslwrap.pygsl_lite_spline_accel_find(self, x)

    def tocobject(self):
        r"""tocobject(pygsl_lite_spline self) -> PyObject *"""
        return _gslwrap.pygsl_lite_spline_tocobject(self)

    def init(self, xa):
        r"""
        init(pygsl_lite_spline self, double const [] xa) -> gsl_error_flag_drop

        Parameters
        ----------
        xa: double const []

        """
        return _gslwrap.pygsl_lite_spline_init(self, xa)

    def eval(self, IN):
        r"""
        eval(pygsl_lite_spline self, double IN) -> double

        Parameters
        ----------
        IN: double

        """
        return _gslwrap.pygsl_lite_spline_eval(self, IN)

    def eval_deriv_e(self, IN):
        r"""
        eval_deriv_e(pygsl_lite_spline self, double IN) -> gsl_error_flag_drop

        Parameters
        ----------
        IN: double

        """
        return _gslwrap.pygsl_lite_spline_eval_deriv_e(self, IN)

    def eval_deriv(self, IN):
        r"""
        eval_deriv(pygsl_lite_spline self, double IN) -> double

        Parameters
        ----------
        IN: double

        """
        return _gslwrap.pygsl_lite_spline_eval_deriv(self, IN)

    def eval_deriv2_e(self, IN):
        r"""
        eval_deriv2_e(pygsl_lite_spline self, double IN) -> gsl_error_flag_drop

        Parameters
        ----------
        IN: double

        """
        return _gslwrap.pygsl_lite_spline_eval_deriv2_e(self, IN)

    def eval_deriv2(self, IN):
        r"""
        eval_deriv2(pygsl_lite_spline self, double IN) -> double

        Parameters
        ----------
        IN: double

        """
        return _gslwrap.pygsl_lite_spline_eval_deriv2(self, IN)

    def eval_integ(self, a, b):
        r"""
        eval_integ(pygsl_lite_spline self, double a, double b) -> double

        Parameters
        ----------
        a: double
        b: double

        """
        return _gslwrap.pygsl_lite_spline_eval_integ(self, a, b)

    def eval_integ_e(self, a, b):
        r"""
        eval_integ_e(pygsl_lite_spline self, double a, double b) -> gsl_error_flag_drop

        Parameters
        ----------
        a: double
        b: double

        """
        return _gslwrap.pygsl_lite_spline_eval_integ_e(self, a, b)

    def eval_e(self, IN):
        r"""
        eval_e(pygsl_lite_spline self, double IN) -> gsl_error_flag_drop

        Parameters
        ----------
        IN: double

        """
        return _gslwrap.pygsl_lite_spline_eval_e(self, IN)

    def eval_vector(self, IN):
        r"""
        eval_vector(pygsl_lite_spline self, gsl_vector const * IN) -> PyObject *

        Parameters
        ----------
        IN: gsl_vector const *

        """
        return _gslwrap.pygsl_lite_spline_eval_vector(self, IN)

    def eval_e_vector(self, IN):
        r"""
        eval_e_vector(pygsl_lite_spline self, gsl_vector const * IN) -> PyObject *

        Parameters
        ----------
        IN: gsl_vector const *

        """
        return _gslwrap.pygsl_lite_spline_eval_e_vector(self, IN)

    def eval_deriv_vector(self, IN):
        r"""
        eval_deriv_vector(pygsl_lite_spline self, gsl_vector const * IN) -> PyObject *

        Parameters
        ----------
        IN: gsl_vector const *

        """
        return _gslwrap.pygsl_lite_spline_eval_deriv_vector(self, IN)

    def eval_deriv2_vector(self, IN):
        r"""
        eval_deriv2_vector(pygsl_lite_spline self, gsl_vector const * IN) -> PyObject *

        Parameters
        ----------
        IN: gsl_vector const *

        """
        return _gslwrap.pygsl_lite_spline_eval_deriv2_vector(self, IN)

    def eval_deriv_e_vector(self, IN):
        r"""
        eval_deriv_e_vector(pygsl_lite_spline self, gsl_vector const * IN) -> PyObject *

        Parameters
        ----------
        IN: gsl_vector const *

        """
        return _gslwrap.pygsl_lite_spline_eval_deriv_e_vector(self, IN)

    def eval_deriv2_e_vector(self, IN):
        r"""
        eval_deriv2_e_vector(pygsl_lite_spline self, gsl_vector const * IN) -> PyObject *

        Parameters
        ----------
        IN: gsl_vector const *

        """
        return _gslwrap.pygsl_lite_spline_eval_deriv2_e_vector(self, IN)

    def eval_integ_vector(self, IN, IN2):
        r"""
        eval_integ_vector(pygsl_lite_spline self, gsl_vector const * IN, gsl_vector const * IN2) -> PyObject *

        Parameters
        ----------
        IN: gsl_vector const *
        IN2: gsl_vector const *

        """
        return _gslwrap.pygsl_lite_spline_eval_integ_vector(self, IN, IN2)

    def eval_integ_e_vector(self, IN, IN2):
        r"""
        eval_integ_e_vector(pygsl_lite_spline self, gsl_vector const * IN, gsl_vector const * IN2) -> PyObject *

        Parameters
        ----------
        IN: gsl_vector const *
        IN2: gsl_vector const *

        """
        return _gslwrap.pygsl_lite_spline_eval_integ_e_vector(self, IN, IN2)

    def name(self):
        r"""name(pygsl_lite_spline self) -> char const *"""
        return _gslwrap.pygsl_lite_spline_name(self)

    def min_size(self):
        r"""min_size(pygsl_lite_spline self) -> unsigned int"""
        return _gslwrap.pygsl_lite_spline_min_size(self)

# Register pygsl_lite_spline in _gslwrap:
_gslwrap.pygsl_lite_spline_swigregister(pygsl_lite_spline)
class pygsl_lite_interp(object):
    r"""Proxy of C pygsl_lite_interp struct."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, T, n):
        r"""
        __init__(pygsl_lite_interp self, gsl_interp_type const * T, size_t n) -> pygsl_lite_interp

        Parameters
        ----------
        T: gsl_interp_type const *
        n: size_t

        """
        _gslwrap.pygsl_lite_interp_swiginit(self, _gslwrap.new_pygsl_lite_interp(T, n))
    __swig_destroy__ = _gslwrap.delete_pygsl_lite_interp

    def init(self, x, y):
        r"""
        init(pygsl_lite_interp self, PyObject * x, PyObject * y) -> gsl_error_flag_drop

        Parameters
        ----------
        x: PyObject *
        y: PyObject *

        """
        return _gslwrap.pygsl_lite_interp_init(self, x, y)

    def name(self):
        r"""name(pygsl_lite_interp self) -> char const *"""
        return _gslwrap.pygsl_lite_interp_name(self)

    def min_size(self):
        r"""min_size(pygsl_lite_interp self) -> unsigned int"""
        return _gslwrap.pygsl_lite_interp_min_size(self)

    def eval_e(self, x):
        r"""
        eval_e(pygsl_lite_interp self, double x) -> gsl_error_flag_drop

        Parameters
        ----------
        x: double

        """
        return _gslwrap.pygsl_lite_interp_eval_e(self, x)

    def eval(self, x):
        r"""
        eval(pygsl_lite_interp self, double x) -> double

        Parameters
        ----------
        x: double

        """
        return _gslwrap.pygsl_lite_interp_eval(self, x)

    def eval_deriv_e(self, x):
        r"""
        eval_deriv_e(pygsl_lite_interp self, double x) -> gsl_error_flag_drop

        Parameters
        ----------
        x: double

        """
        return _gslwrap.pygsl_lite_interp_eval_deriv_e(self, x)

    def eval_deriv(self, x):
        r"""
        eval_deriv(pygsl_lite_interp self, double x) -> double

        Parameters
        ----------
        x: double

        """
        return _gslwrap.pygsl_lite_interp_eval_deriv(self, x)

    def eval_deriv2_e(self, x):
        r"""
        eval_deriv2_e(pygsl_lite_interp self, double x) -> gsl_error_flag_drop

        Parameters
        ----------
        x: double

        """
        return _gslwrap.pygsl_lite_interp_eval_deriv2_e(self, x)

    def eval_deriv2(self, x):
        r"""
        eval_deriv2(pygsl_lite_interp self, double x) -> double

        Parameters
        ----------
        x: double

        """
        return _gslwrap.pygsl_lite_interp_eval_deriv2(self, x)

    def eval_integ_e(self, a, b):
        r"""
        eval_integ_e(pygsl_lite_interp self, double a, double b) -> gsl_error_flag_drop

        Parameters
        ----------
        a: double
        b: double

        """
        return _gslwrap.pygsl_lite_interp_eval_integ_e(self, a, b)

    def eval_integ(self, a, b):
        r"""
        eval_integ(pygsl_lite_interp self, double a, double b) -> double

        Parameters
        ----------
        a: double
        b: double

        """
        return _gslwrap.pygsl_lite_interp_eval_integ(self, a, b)

    def accel_reset(self):
        r"""accel_reset(pygsl_lite_interp self) -> gsl_error_flag_drop"""
        return _gslwrap.pygsl_lite_interp_accel_reset(self)

    def accel_find(self, x):
        r"""
        accel_find(pygsl_lite_interp self, double x) -> size_t

        Parameters
        ----------
        x: double

        """
        return _gslwrap.pygsl_lite_interp_accel_find(self, x)

# Register pygsl_lite_interp in _gslwrap:
_gslwrap.pygsl_lite_interp_swigregister(pygsl_lite_interp)
cvar = _gslwrap.cvar
gsl_interp_linear = cvar.gsl_interp_linear
gsl_interp_polynomial = cvar.gsl_interp_polynomial
gsl_interp_cspline = cvar.gsl_interp_cspline
gsl_interp_cspline_periodic = cvar.gsl_interp_cspline_periodic
gsl_interp_akima = cvar.gsl_interp_akima
gsl_interp_akima_periodic = cvar.gsl_interp_akima_periodic


def gsl_interp_bsearch(x_array, x, index_lo, index_hi):
    r"""
    gsl_interp_bsearch(double const [] x_array, double x, size_t index_lo, size_t index_hi) -> size_t

    Parameters
    ----------
    x_array: double const []
    x: double
    index_lo: size_t
    index_hi: size_t

    """
    return _gslwrap.gsl_interp_bsearch(x_array, x, index_lo, index_hi)

